### PR TITLE
fix: self-dependency in DAG-MPI and re-correct job config creation position.

### LINKED ISSUE #164: [BUG] mpi-operator has problems about DAG scheduling
**What happened**: mpi job cannot work, the worker pod is blocking cause the configmap miss

**What you expected to happen**: mpi job works successful

**How to reproduce it**: run a mpi example with launcher and worker 

**Environment**:
- KubeDL version: master branch, latest commit

**Anything else we need to know?**:

First, there is a bug in the following code.

https://github.com/kubedl-io/kubedl/blob/6eb94727ef485f143e04fc94f5ce31d92b8796b5/apis/training/v1alpha1/mpijob_default.go#L70-L81

```golang
job.Spec.MPIReplicaSpecs[MPIReplicaTypeLauncher].DependOn = []v1.DAGCondition{
			{Upstream: MPIReplicaTypeLauncher, OnPhase: corev1.PodRunning},
		}
```

should be changed to 

```golang
job.Spec.MPIReplicaSpecs[MPIReplicaTypeLauncher].DependOn = []v1.DAGCondition{
			{Upstream: MPIReplicaTypeWorker, OnPhase: corev1.PodRunning},
		}
```

Second, even though fix the bug above. But the worker pod replies the configmap which create by following code. But because the dag scheduling enable, the logic will not reach here.

https://github.com/kubedl-io/kubedl/blob/6eb94727ef485f143e04fc94f5ce31d92b8796b5/controllers/mpi/pod.go#L60-L66

So, my opinion is disable/delete the dag scheduling in mpi job. The related discuss is here. https://github.com/kubedl-io/kubedl/issues/82#issuecomment-884229276

Looking forward to your reply.

### PR DESCRIPTION
**Pull request by SimonCqk**
### Ⅰ. Describe what this PR does

1. fix Launcher self-dependency in DAG-MPI mode.
2. re-correct job config creation position in control flow.

### II. Does this pull request fix one issue?

fix #164

### CODE REVIEW

**Comment by SimonCqk** [comment]
@jian-he @HeGaoYuan plz take a review

File: controllers/mpi/mpijob_controller.go [hunk 1]
```diff
@@ -216,6 +217,20 @@ func (r *MPIJobReconciler) SetClusterSpec(ctx context.Context, job interface{},
...
 		return fmt.Errorf("%+v is not a type of MPIJob", job)
 	}
+	workerReplicas := int32(0)
+	if workerSpec := mpiJob.Spec.MPIReplicaSpecs[training.MPIReplicaTypeWorker]; workerSpec != nil && workerSpec.Replicas != nil {
+		workerReplicas = *workerSpec.Replicas
+	}
+	if launcherSpec, ok := mpiJob.Spec.MPIReplicaSpecs[training.MPIReplicaTypeLauncher]; ok && launcherSpec != nil {
+		// MPIJob ensures job-attached configuration is kept by ConfigMap when launcher
+		// neither succeed nor failed.
+		isGPULauncher := resource_utils.PodRequestsForGPU(&corev1.Pod{Spec: launcherSpec.Template.Spec}) && launcherRunsWorkload
```
Comment (HeGaoYuan) [inline controllers/mpi/mpijob_controller.go:227]: As we've discussed(https://github.com/kubedl-io/kubedl/pull/129), directly use the launcherRunsWorkload variable is better?

File: controllers/mpi/mpijob_controller.go [hunk 2]
```diff
@@ -216,6 +217,20 @@ func (r *MPIJobReconciler) SetClusterSpec(ctx context.Context, job interface{},
...
+		log.Info("launcher of MPIJob: ", mpiJob.Namespace+"/"+mpiJob.Name, " generate job config.")
+		_, err := r.getOrCreateJobConfig(mpiJob, workerReplicas, isGPULauncher)
```
Comment (HeGaoYuan) [inline controllers/mpi/mpijob_controller.go:229]: https://github.com/kubedl-io/kubedl/blob/6eb94727ef485f143e04fc94f5ce31d92b8796b5/controllers/mpi/pod.go#L57-L67
Does these code need anymore?

**Review by HeGaoYuan — COMMENTED** [review]
@SimonCqk Here is my opinion

File: controllers/mpi/mpijob_controller.go (hunk 1 above)
Comment (SimonCqk) [reply controllers/mpi/mpijob_controller.go]: done

File: controllers/mpi/mpijob_controller.go (hunk 2 above)
Comment (SimonCqk) [reply controllers/mpi/mpijob_controller.go]: removed

**Comment by HeGaoYuan** [comment]
lgtm

**Comment by jian-he** [comment]
lgtm

**Comment by jian-he** [comment]
thanks @HeGaoYuan for the review !
